const mongoose = require("mongoose");

const companySchema = new mongoose.Schema({
  "name": String,
  "permalink": String,
  "crunchbase_url": String,
  "homepage_url": String,
  "blog_url": String,
  "blog_feed_url": String,
  "twitter_username": String,
  "category_code": String,
  "number_of_employees": Number,
  "founded_year": Number,
  "founded_month": Number,
  "founded_day": Number,
  "deadpooled_year": Number,
  "deadpooled_month": Number,
  "deadpooled_day": Number,
  "deadpooled_url": String,
  "tag_list": String,
  "alias_list": String,
  "email_address": String,
  "phone_number": String,
  "description": String,

  "overview": String,
  "image": {},
  "products": [],
  "relationships": [],
  "competitions": [],
  "providerships": [],
  "total_money_raised": String,
  "funding_rounds": [],
  "investments": [],
  "acquisition": {},
  "acquisitions": [],
  "offices": [],
  "milestones": [],
  "ipo": {},
  "video_embeds": [],
  "screenshots": [],
  "external_links": [{
    "external_url": String,
    "title": String
  }],
  "partners": []
});
